repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [ python ]
  - repo: local
    hooks:
      - id: unittest
        name: Full release sequence
        entry: python3 python/unit_test.py
        language: python
        'types': [ python ]
        pass_filenames: false
        stages: [ commit ]
